#!/bin/bash
ROOT=$(git rev-parse --show-toplevel)
cd "${ROOT}"

image="golang:1.16-rc-alpine"

docker run -t --rm \
  -u $(id -u):$(id -g) \
  -v ${ROOT}:/src \
  -w /src \
  -e CGO_ENABLED=0 \
  -e GOOS=darwin \
  -e GOARCH=arm64 \
  -e GOCACHE="/src/.cache" \
  golang:1.16-rc-alpine \
  go build -mod=vendor -o gokvm.osx ./cmd/gokvm/
